/*
 * The main class
 */
package Vista;

import Negocio.Casino;



import java.awt.Cursor;

import java.awt.Point;
import java.awt.Toolkit;

import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;


/**
 *
 * @author CORE I3
 */
public class FormCasinoPrincipal extends javax.swing.JFrame {  //ESTE ES EL FORMULARIO PRINCIPAL DONDE SE VA A COMUNICAR CON EL NEGOCIO

    private Casino myCasino ;
    
    

    public Casino getMyCasino() {
        return myCasino;
    }
    /**
     * Creates new form FormCasinoPrincipal
     */
    
    
    public FormCasinoPrincipal() {
        initComponents();
        
        this.myCasino= new Casino();
this.cambiarMouse();
        this.setResizable(false);
        this.setTitle("Casino Internacional");
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono.jpg.png")).getImage());
//        this.setSize(new Dimension(360,360));
        //codigo del fondo
        ((JComponent)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/Imagenes/fondo 3.jpg")); 
        JLabel fondo= new JLabel(); fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER); 
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
      
        int cantJugadores = this.myCasino.enumerar(0);
      this.validarBlackJack(cantJugadores);
        
      
      

      
      
      
    }
public void mostrarMsg(String msg){
    JOptionPane.showMessageDialog(this, msg, "Casino", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/Imagenes/icono casino.png"));
}
private void cambiarMouse(){
    ImageIcon im= new ImageIcon(getClass().getResource("/Imagenes/mouse.png"));
    Toolkit tk =Toolkit.getDefaultToolkit();

Cursor cursor=tk.createCustomCursor(im.getImage(), new Point(1,1), "Cursor");
    this.setCursor(cursor);
}
    
    public void validarBlackJack(int a ){
        if (a< 2) {
            this.cmdBlackJack.setEnabled(false);
        }else{
            this.cmdBlackJack.setEnabled(true);
        }
        
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmdOpcionesJugador = new javax.swing.JButton();
        cmdListados = new javax.swing.JButton();
        cmdBlackJack = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casino_logo_smaller.png"))); // NOI18N

        cmdOpcionesJugador.setBackground(new java.awt.Color(153, 0, 0));
        cmdOpcionesJugador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdOpcionesJugador.setForeground(new java.awt.Color(255, 255, 255));
        cmdOpcionesJugador.setText(" Opciones Jugador");
        cmdOpcionesJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOpcionesJugadorActionPerformed(evt);
            }
        });

        cmdListados.setBackground(new java.awt.Color(153, 0, 0));
        cmdListados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdListados.setForeground(new java.awt.Color(255, 255, 255));
        cmdListados.setText("Listados");
        cmdListados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdListadosActionPerformed(evt);
            }
        });

        cmdBlackJack.setBackground(new java.awt.Color(153, 0, 0));
        cmdBlackJack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdBlackJack.setForeground(new java.awt.Color(255, 255, 255));
        cmdBlackJack.setText("BlackJack");
        cmdBlackJack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdBlackJack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBlackJackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmdBlackJack, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdListados, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdOpcionesJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(cmdListados)
                .addGap(30, 30, 30)
                .addComponent(cmdBlackJack)
                .addGap(34, 34, 34)
                .addComponent(cmdOpcionesJugador)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBlackJackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBlackJackActionPerformed
        FormBlackJack blackJack = new FormBlackJack(this);
        this.setVisible(false);

        blackJack.setVisible(true);
    }//GEN-LAST:event_cmdBlackJackActionPerformed

    private void cmdOpcionesJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOpcionesJugadorActionPerformed
        FormJugador myFormJugador= new FormJugador(this);
        this.setVisible(false);
        myFormJugador.setVisible(true);
    }//GEN-LAST:event_cmdOpcionesJugadorActionPerformed

    private void cmdListadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdListadosActionPerformed
        FormListados casinoOp= new FormListados(this);
        this.setVisible(false);
        casinoOp.setVisible(true);
    }//GEN-LAST:event_cmdListadosActionPerformed

  
    
    
  
    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCasinoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCasinoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCasinoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCasinoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCasinoPrincipal().setVisible(true);
            }
        });
    }

  
   
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBlackJack;
    private javax.swing.JButton cmdListados;
    private javax.swing.JButton cmdOpcionesJugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
